### PR TITLE
Adding a default export to client.js

### PR DESCRIPTION
**Pull request by oztune**
In order to avoid breaking user code that does  `import topojson from 'topojson'`. See https://github.com/mbostock/topojson/commit/6770d3c7d41594d17865b3bebfed3a9d2b09e0e8 for discussion.

### CODE REVIEW

**Comment by mbostock** [comment]
Did you test this? I don’t think Rollup transpiles any ES2015 language features except for `import` and `export`, so your use of the shorthand object syntax (`{foo}` in place of `{foo: foo}`) looks like it will break older environments.

**Comment by oztune** [comment]
It's actually not shorthand, `export { x }` is the only way to do it (confused me too initially): https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export

I tested it by running `npm test` and also `npm install` just to be safe.

**Comment by mbostock** [comment]
They are two different things.

`export {foo}` exports the symbol foo.

`export default {foo}` exports the object `{foo: foo}` as the default export.

I’m saying you need to say `export default {foo: foo}` to support older browsers, since Rollup won’t transpile `{foo}` to `{foo: foo}`.

**Comment by oztune** [comment]
...I did test it on a new version of node, so I'll just update the syntax momentarily

**Comment by oztune** [comment]
Ok, changed it and ran the tests again

**Comment by oztune** [comment]
Should this PR also update the version to 1.6.28?

**Comment by mbostock** [comment]
No, I’ll do that when cutting a release.

**Comment by mbostock** [comment]
This pull request seems to have no effect on the generated bundle. Is that the desired result? As in, do you only care about fixing consumers of the ES2015 source? Or do you want the generated UMD bundle to have both named and default exports?

I’m not sure how Rollup handles modules that have both named and default exports. It looks like there’s an [exports option](https://github.com/rollup/rollup/wiki/JavaScript-API#exports) the defaults to “auto”. But it doesn’t seem to be generating an output object with a `default` property on it.

The other thing is that Rollup doesn’t use `client.js` as the entry point for the bundle. It uses `build/bundle.js`, which is used to insert the version number and looks like this:

```js
var version = "1.6.27";
export * from "../client";
export {version};
```

Default exports aren’t re-exported by `export * from …`. [(source)](http://exploringjs.com/es6/leanpub-endnotes.html#fn-modules_2)

There are ways we can fix this, of course, I just don’t know what the desired result is.

**Comment by oztune** [comment]
I think we'll need to move the `export default` part to `build/bundle.js` then. I'll give it a try.

**Comment by oztune** [comment]
So, messing around with the `pretest` script, I can get it to generate this output for `build/bundle.js`:

```
var version = "1.6.27";
export * from "../client"; export {version};
// [These two lines are new]
import defaultExport from "../client";
export default defaultExport;
```

Does that seem ok? It feels kind of hacky.

**Comment by mbostock** [comment]
Can you answer my earlier question: What is the desired result? Do you only care about fixing consumers of the ES2015 source? Or do you want the generated UMD bundle to have both named and default exports?

**Comment by mbostock** [comment]
As part of the imminent TopoJSON 2.0 release, I’ve moved the [topojson-client](https://github.com/topojson/topojson-client) library to a separate package, and I am about to bump the major version of this package. I don’t think it makes sense to apply this to the 2.0 release in the new location. I suppose we could still do a patch 1.6.x release for the old library, but as this thread died down it does not appear to be strong demand.

**Pull request closed without merging**
